title: Peter Malope
logo: GitHub - Profile Pic Circular.jpg
# description: Peter Malope is an aspiring Software Engineer who is currently in the process of completing his Diploma in Computer Sciences from Tshwane University of Technology. He believes that his academic accomplishments, complemented by practical experience and fieldwork, have furnished him with the necessary tools to excel in the realms of Software Engineering, IT, and Computer Sciences.
# show_downloads: true
theme: jekyll-theme-minimal